name: Docker Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ secrets.DOCKERHUB_DISPLAYNAME }}/${{ secrets.IMAGE_NAME }}:test

      - name: Test Docker image
        run: |
          docker run ${{ secrets.DOCKERHUB_DISPLAYNAME }}/${{ secrets.IMAGE_NAME }}:test CloudflareST -h | grep -q "XIU2/CloudflareSpeedTest" && echo "Test passed" || exit 1

      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_DISPLAYNAME }}/${{ secrets.IMAGE_NAME }}:latest